### ISSUE TITLE
Support Obsidian Callouts

### ISSUE THREAD

**Issue by simonla82** [samuele-cozzi/obsidian-marp-slides#105]
Thanks for the amazing plugin! I really like the easy syntax of that plugin.

One feature I would love to have is the possibility to use [Obsidian Callouts](https://help.obsidian.md/Editing+and+formatting/Callouts) in the slides, as I make heavy use of them in my notes. Do you think that is possible without deviating too much from the Marp core?

**Comment by wenbopeng** [comment]
This depends on your Marp theme, not this plugin. See the theme you need [favourhong/Awesome-Marp: custom Marp templates with a selection of over a dozen themes](https://github.com/favourhong/Awesome-Marp)
