### ISSUE TITLE
support absolute path in vault

### ISSUE THREAD

**Issue by calmwaves111** [samuele-cozzi/obsidian-marp-slides#106]
file and link settings are not relative paths, but absolute paths in vault, and I cannot render images properly in MARP

**Comment by samuele-cozzi** [comment]
Thank you for your interest in our project and for taking the time to report this issue. To better understand the issue and assist you in resolving it, could you please provide some additional details?

**Comment by calmwaves111** [comment]
> Thank you for your interest in our project and for taking the time to report this issue. To better understand the issue and assist you in resolving it, could you please provide some additional details?

My settings in OBSIDIAN are as follows. Can I support this type of link
![image](https://github.com/samuele-cozzi/obsidian-marp-slides/assets/56907077/b0987a87-caf7-449d-a0de-39fac43d6591)


- obsidianfold（vault）
	- Afolder
	- Bfolder
		- assets
			- example.png
		- test.md
	- Cfolder

in `test.md`，the `example.png` is imported by this link
```
![example.png](Bfolder/assets/example.png)
```
