### ISSUE TITLE
a very simple question

### ISSUE THREAD

**Issue by JunseokLee3** [samuele-cozzi/obsidian-marp-slides#107]
![image](https://github.com/samuele-cozzi/obsidian-marp-slides/assets/62575381/91bf0865-c131-426f-b634-0294248681e9)

Hello. I'm a novice developer.
I think your plug-in is really cool.
But I'm so curious about the plug-in you showed me.
Can you tell me?

**Comment by samuele-cozzi** [comment]
😄  it is clipboard history in windows 11. Instead paste with `Ctrl+V`, click `Windows Key+V` and follow the instruction to enable 😄
