### ISSUE TITLE
Add two column options for Beamer theme

### ISSUE THREAD

**Issue by PKDmeDEV** [samuele-cozzi/obsidian-marp-slides#125]
Hi,
In some of the provided themes, there are options of multiple columns. However, I couldn't see such option for beamer theme. Could you please help me with this.

Thanks.

**Comment by samuele-cozzi** [comment]
The themes you've noticed, including those with multiple columns, were sourced from the internet and incorporated for testing purposes of the plugin. As of now, adding multiple columns to the Beamer theme is not a priority in our development roadmap.

You can use the background images to have two column slides:

```
![bg left:33%](https://picsum.photos/720?image=27)

# Split backgrounds

The space of a slide content will shrink to the right side.
```

[Examples](https://github.com/marp-team/marpit/blob/main/docs/image-syntax.md#split-backgrounds)
