### ISSUE TITLE
v0.42.0 breaks other plugin's suggestion (completion)

### ISSUE THREAD

**Issue by gdm257** [samuele-cozzi/obsidian-marp-slides#130]
When I upgrade marp slides to 0.42.0, the editor code completions provided by other plugins don't work as if issue #129 

I'm sure this problem was introduced in 0.42.0, where 0.41.0 works well. It looks like [`src/main.ts`](https://github.com/samuele-cozzi/obsidian-marp-slides/compare/0.41.0...0.42.0#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR81) cleans other suggestions by `registerEditorSuggest`

I'm not family with obsidian API, is there a solution like appending suggestions to existing?

**Comment by samuele-cozzi** [comment]
Thank you for reaching out and expressing interest in the project. Could you please share some Obsidian plugin that you use with suggestion, so I will fix an test it very soon?

**Comment by gdm257** [comment]
> Thank you for reaching out and expressing interest in the project. Could you please share some Obsidian plugin that you use with suggestion, so I will fix an test it very soon?

Sure! Here are  some plugins:

- `Slash commands`: official plugin for suggestion of `/`
- `FuzzyTag`: tag suggestion in frontmatter
- `Completr`: LaTeX suggestion

And fast use case

```
---
# FuzzyTag
tags:
- pattern
---

# Slash commands
/pattern

# Completr
$alpha$
```
