### ISSUE TITLE
Similarities with Advanced Slides plugin?

### ISSUE THREAD

**Issue by agentlibre** [samuele-cozzi/obsidian-marp-slides#133]
Advanced Slides plugin has recently been discontinued: https://forum.obsidian.md/t/discontinued-advanced-slides-create-markdown-based-reveal-js-presentations-in-obsidian/28243/160

It is a shame since I have used it extensively and all my class presentations are formatted to suit this plugin.

I have noticed your plugin, which seems very tidy and promising. However, it seems you have taken a different approach and synthax.

Could you explain if there is any way for me to make my Advanced Slides notes compatible with Marp Slides? What are the main differences in the approach? Do you plan on having options to add images, unlisted fragments, etc. ? 

Thank you for the good work!

**Comment by samuele-cozzi** [comment]
The main difference between the two plugins is that the Advanced slides plugin is based on the [revealjs](https://revealjs.com/) engine, meanwhile, Marp Slides is based on [Marp](https://marp.app/) engine.

The syntax is quite similar, but I don't know how to migrate from one to the other. I understand that Revealjs use more JavaScript, meanwhile, Marp use more CSS, and for these reasons, the Marp slides are more static, but cleaner, in my opinion.

Thank you very much for your interest in our plugin
