### ISSUE TITLE
Open themes .css files 

### ISSUE THREAD

**Issue by jcmoral90** [samuele-cozzi/obsidian-marp-slides#137]
My obsidian vault does not recognize the .css files. How can I enable the .css themes you attach in your github? Should I install some complementary plugin? Think that my vault has only Marp's plugin installed as a test.

https://samuele-cozzi.github.io/obsidian-marp-slides/23.SlidesCustomTheme.html

Regards

**Comment by samuele-cozzi** [comment]
I use [vscode](https://code.visualstudio.com/) to edit the css files. After edit the css, I reload the preview of the deck
