### ISSUE TITLE
Mannual way of installing lib

### ISSUE THREAD

**Issue by yanggthomas** [samuele-cozzi/obsidian-marp-slides#151]
Hi, I am encountering a problem with preview buttom. From developer tools, I get of "no such file or directory, open 'xxxx/.obsidian/plugins/marp-slides/lib3/bespoke.js". I checked "xxxx/.obsidian/plugins/marp-slides" and there is no lib3 content.

How can the lib be installed mannually? My plugin version is 0.45.5

**Comment by samuele-cozzi** [comment]
Please close and reopen obsidian. If doesn't work, you can find the library [here](https://github.com/samuele-cozzi/obsidian-marp-slides/releases/tag/lib-v3) in the zip file

**Comment by yanggthomas** [comment]
Hi, thanks for your reply. I did download library files and unzip them to 'xxxx/.obsidian/plugins/marp-slides/lib3/'. However, I cannot use markdown-it plugins. I get 'The specified engine has not resolved' error.

According to https://github.com/marp-team/marp-cli/issues/224, I tried to install with "npm install" in 'xxxx/.obsidian/plugins/marp-slides/lib3/', but the error remains.

I am not familiar with npm and node.js. Perhaps my installation is wrong？

**Comment by samuele-cozzi** [comment]
This is the folder structure of my vault:
![image](https://github.com/samuele-cozzi/obsidian-marp-slides/assets/2479040/ba9d7fc5-090c-4f11-b0bb-bb9e888abb2e)

the lib folder of the zip will be renamed in lib3. No need of npm or node

I hope this is helpful :-)
