### ISSUE TITLE
Can't export style with css tag

### ISSUE THREAD

**Issue by Tongzhao9417** [samuele-cozzi/obsidian-marp-slides#96]
Hi, I found something error when I want to export to html with CSS tag in slide. Here is the examples.
```
---
theme: gaia
paginate: true
backgroundColor: #fff
backgroundImage: url('https://marp.app/assets/hero-background.svg')
style: @import url('https://unpkg.com/tailwindcss@^2/dist/utilities.min.css')
---

<div class="grid grid-cols-2 gap-4">
<div>

## Column 1

Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas eveniet, corporis commodi vitae accusamus obcaecati dolor corrupti eaque id numquam officia velit sapiente incidunt dolores provident laboriosam praesentium nobis culpa.

</div>
<div>

## Column 2

Tempore ad exercitationem necessitatibus nulla, optio distinctio illo non similique? Laborum dolor odio, ipsam incidunt corrupti quia nemo quo exercitationem adipisci quidem nesciunt deserunt repellendus inventore deleniti reprehenderit at earum.

</div>
</div>

```
If I used VS code, here is the output looks like. 
<img width="1382" alt="image" src="https://github.com/samuele-cozzi/obsidian-marp-slides/assets/42951960/b129cf80-0f55-480c-90a9-6548e957b354">
 That is the marp in obsidian export:
<img width="1404" alt="image" src="https://github.com/samuele-cozzi/obsidian-marp-slides/assets/42951960/5e056da8-7f08-428c-8ef0-8962a0f9e453">

**Comment by samuele-cozzi** [comment]
Thank you for bringing this issue to my attention. I appreciate your help in improving our project. I have fixed the issue in a new version of plugin.

Please remember to enable the HTML property:

![image](https://github.com/samuele-cozzi/obsidian-marp-slides/assets/2479040/5fd7f6af-dc14-49ec-b202-0b6e1f08c5ff)
